query RunInput {
  cart {
    lines {
      id
      quantity
      merchandise {
        __typename
        ... on ProductVariant {
          id
          product {
            id
            bundleDiscount: metafield(
              namespace: "tangbuy_bundle"
              key: "discount_percent"
            ) {
              value
            }
            comboConfig: metafield(namespace: "tangbuy_combo", key: "config") {
              value
            }
          }
        }
      }
    }
  }
}
